Repository plone/plone.recipe.zope2instance, pull requests merged in 2018-11, with the labels that each got.

#52 Build a bin/instance script that works with Zope 4 + WSGI
  CHANGES.rst
  README.rst
  src/plone/recipe/zope2instance/ctl.py
  src/plone/recipe/zope2instance/recipe.py
  src/plone/recipe/zope2instance/tests/test_wsgischema.py
  src/plone/recipe/zope2instance/wsgischema.xml
Labels: 23 status: testing, 32 needs: review

#58 Fix ReST.
  CHANGES.rst
Labels: 01 type: bug, 32 needs: review

#63 Add support for Python 3.7 while dropping support for Python 3.5.
  .travis.yml
  CHANGES.rst
  MANIFEST.in
  README.rst
  setup.cfg
  setup.py
  tox.ini
Labels: 04 type: enhancement, 32 needs: review
